/**
 * © 2025 MyDebugger Contributors – MIT License
 */

export interface QRStylePreset {
  group: string;
  name: string;
  darkColor?: string;
  lightColor?: string;
  start?: string;
  end?: string;
  angle?: string;
  dotStyle: string;
  eyeStyle: string;
  logo?: string;
}

export const qrStylePresets: QRStylePreset[] = [
  // Group 1: Neutral & Professional
  {
    group: 'Neutral & Professional',
    name: 'Classic Neutral',
    darkColor: '#000000',
    lightColor: '#ffffff',
    dotStyle: 'square',
    eyeStyle: 'square',
    logo: 'Optional black/white',
  },
  {
    group: 'Neutral & Professional',
    name: 'Soft Slate',
    darkColor: '#4b5563',
    lightColor: '#f9fafb',
    dotStyle: 'rounded',
    eyeStyle: 'bold',
    logo: 'Gray or mono logo',
  },
  {
    group: 'Neutral & Professional',
    name: 'Navy Authority',
    darkColor: '#1e3a8a',
    lightColor: '#ffffff',
    dotStyle: 'dots',
    eyeStyle: 'frame',
    logo: 'Blue-toned icon',
  },
  {
    group: 'Neutral & Professional',
    name: 'Modern Ink',
    darkColor: '#111827',
    lightColor: '#e5e7eb',
    dotStyle: 'square',
    eyeStyle: 'outline',
    logo: 'No logo preferred',
  },
  {
    group: 'Neutral & Professional',
    name: 'Minimal Warm',
    darkColor: '#374151',
    lightColor: '#fefce8',
    dotStyle: 'round',
    eyeStyle: 'square',
    logo: 'Flat icon (light gray)',
  },
  // Group 2: Gradient Aesthetics
  {
    group: 'Gradient Aesthetics',
    name: 'Sunset Warm',
    start: '#ef4444',
    end: '#f97316',
    angle: '294°',
    dotStyle: 'dots',
    eyeStyle: 'square',
    logo: 'White logo',
  },
  {
    group: 'Gradient Aesthetics',
    name: 'Horizon Blue',
    start: '#60a5fa',
    end: '#38bdf8',
    angle: '90°',
    dotStyle: 'circle',
    eyeStyle: 'frame',
    logo: 'Blue or white',
  },
  {
    group: 'Gradient Aesthetics',
    name: 'Aurora Electric',
    start: '#8b5cf6',
    end: '#22d3ee',
    angle: '60°',
    dotStyle: 'squircle',
    eyeStyle: 'cyberline',
    logo: 'Neon icon',
  },
  {
    group: 'Gradient Aesthetics',
    name: 'Midnight Lava',
    start: '#dc2626',
    end: '#facc15',
    angle: '270°',
    dotStyle: 'square',
    eyeStyle: 'bold',
    logo: 'No logo',
  },
  {
    group: 'Gradient Aesthetics',
    name: 'Bubble Sunrise',
    start: '#fda4af',
    end: '#fcd34d',
    angle: '135°',
    dotStyle: 'rounded',
    eyeStyle: 'dot-in-dot',
    logo: 'Icon with white fill',
  },
  // Group 3: Tech, SaaS & Business Cards
  {
    group: 'Tech, SaaS & Business Cards',
    name: 'Linked Slate',
    darkColor: '#0a66c2',
    lightColor: '#f3f4f6',
    dotStyle: 'square',
    eyeStyle: 'frame',
    logo: 'Flat',
  },
  {
    group: 'Tech, SaaS & Business Cards',
    name: 'SaaS Purple',
    darkColor: '#7c3aed',
    lightColor: '#f5f3ff',
    dotStyle: 'rounded',
    eyeStyle: 'drop',
    logo: 'Purple circle logo',
  },
  {
    group: 'Tech, SaaS & Business Cards',
    name: 'Bootstrap Blue',
    darkColor: '#0d6efd',
    lightColor: '#ffffff',
    dotStyle: 'square',
    eyeStyle: 'square',
    logo: 'Icon in circle',
  },
  {
    group: 'Tech, SaaS & Business Cards',
    name: 'Dark Terminal',
    darkColor: '#22c55e',
    lightColor: '#111827',
    dotStyle: 'pixel',
    eyeStyle: 'dot-in-dot',
    logo: 'Dev logo',
  },
  {
    group: 'Tech, SaaS & Business Cards',
    name: 'Matrix Line',
    darkColor: '#10b981',
    lightColor: '#f0fdf4',
    dotStyle: 'line',
    eyeStyle: 'outline',
    logo: 'No logo',
  },
  // Group 4: Music, Creators, Gen Z
  {
    group: 'Music, Creators, Gen Z',
    name: 'Vaporwave Fade',
    start: '#ec4899',
    end: '#8b5cf6',
    lightColor: '#fce7f3',
    dotStyle: 'squircle',
    eyeStyle: 'cyberline',
    logo: 'SVG icon',
  },
  {
    group: 'Music, Creators, Gen Z',
    name: 'EDM Neon',
    darkColor: '#facc15',
    lightColor: '#111827',
    dotStyle: 'circle',
    eyeStyle: 'drop',
    logo: 'Bold mono',
  },
  {
    group: 'Music, Creators, Gen Z',
    name: 'Insta Pop',
    darkColor: '#c026d3',
    lightColor: '#faf5ff',
    dotStyle: 'blob',
    eyeStyle: 'dot-in-dot',
    logo: 'Pastel brand',
  },
  {
    group: 'Music, Creators, Gen Z',
    name: 'Techno Pulse',
    darkColor: '#06b6d4',
    lightColor: '#0f172a',
    dotStyle: 'squircle',
    eyeStyle: 'bold',
    logo: 'High contrast',
  },
  {
    group: 'Music, Creators, Gen Z',
    name: 'Retro Disc',
    darkColor: '#f43f5e',
    lightColor: '#ffe4e6',
    dotStyle: 'dots',
    eyeStyle: 'square',
    logo: 'White logo',
  },
  // Group 5: Nature, Wellness, Organic
  {
    group: 'Nature, Wellness, Organic',
    name: 'Forest Calm',
    darkColor: '#166534',
    lightColor: '#ecfdf5',
    dotStyle: 'pill',
    eyeStyle: 'square',
    logo: 'Leaf icon',
  },
  {
    group: 'Nature, Wellness, Organic',
    name: 'Eco Mint',
    darkColor: '#a7f3d0',
    lightColor: '#f0fdfa',
    dotStyle: 'dots',
    eyeStyle: 'rounded',
    logo: 'Soft mono',
  },
  {
    group: 'Nature, Wellness, Organic',
    name: 'Stone Zen',
    darkColor: '#6b7280',
    lightColor: '#f3f4f6',
    dotStyle: 'square',
    eyeStyle: 'outline',
    logo: 'Simple sans',
  },
  {
    group: 'Nature, Wellness, Organic',
    name: 'Morning Dew',
    darkColor: '#22d3ee',
    lightColor: '#f0f9ff',
    dotStyle: 'circle',
    eyeStyle: 'frame',
    logo: 'Nature mark',
  },
  {
    group: 'Nature, Wellness, Organic',
    name: 'Herbal Warmth',
    darkColor: '#84cc16',
    lightColor: '#fef9c3',
    dotStyle: 'squircle',
    eyeStyle: 'dot-in-dot',
    logo: 'No logo',
  },
  // Group 6: Elegant, Minimal, Luxury
  {
    group: 'Elegant, Minimal, Luxury',
    name: 'Luxe Gold',
    darkColor: '#d4af37',
    lightColor: '#ffffff',
    dotStyle: 'diamond',
    eyeStyle: 'line square',
    logo: 'Monogram',
  },
  {
    group: 'Elegant, Minimal, Luxury',
    name: 'Monochrome Light',
    darkColor: '#e5e7eb',
    lightColor: '#ffffff',
    dotStyle: 'circle',
    eyeStyle: 'drop',
    logo: 'No icon',
  },
  {
    group: 'Elegant, Minimal, Luxury',
    name: 'Soft Champagne',
    darkColor: '#fde68a',
    lightColor: '#fff7ed',
    dotStyle: 'pill',
    eyeStyle: 'outline',
    logo: 'Serif logo',
  },
  {
    group: 'Elegant, Minimal, Luxury',
    name: 'Fashion Beige',
    darkColor: '#d6d3d1',
    lightColor: '#ffffff',
    dotStyle: 'squircle',
    eyeStyle: 'bold',
    logo: 'Brand mark',
  },
  {
    group: 'Elegant, Minimal, Luxury',
    name: 'Charcoal Shadow',
    darkColor: '#1f2937',
    lightColor: '#f3f4f6',
    dotStyle: 'square',
    eyeStyle: 'rounded',
    logo: 'White icon',
  },
  // Group 7: Culture, Event, Celebration
  {
    group: 'Culture, Event, Celebration',
    name: 'Lunar Red',
    darkColor: '#dc2626',
    lightColor: '#fff7ed',
    dotStyle: 'diamond',
    eyeStyle: 'square',
    logo: 'CNY, luck',
  },
  {
    group: 'Culture, Event, Celebration',
    name: 'Sakura Petal',
    darkColor: '#fda4af',
    lightColor: '#fff1f2',
    dotStyle: 'round',
    eyeStyle: 'dot-in-dot',
    logo: 'Spring fest',
  },
  {
    group: 'Culture, Event, Celebration',
    name: 'Thai Heritage',
    darkColor: '#d97706',
    lightColor: '#fffbea',
    dotStyle: 'squircle',
    eyeStyle: 'bold',
    logo: 'Royal events',
  },
  {
    group: 'Culture, Event, Celebration',
    name: 'Diwali Glow',
    darkColor: '#f59e0b',
    lightColor: '#fff7ed',
    dotStyle: 'pill',
    eyeStyle: 'drop',
    logo: 'Festival QR',
  },
  {
    group: 'Culture, Event, Celebration',
    name: 'Christmas Pine',
    darkColor: '#166534',
    lightColor: '#fff7f0',
    dotStyle: 'circle',
    eyeStyle: 'square',
    logo: 'Holiday sales',
  },
  // Group 8: Experimental, Creative Showcase
  {
    group: 'Experimental, Creative Showcase',
    name: 'Tech Melt',
    start: '#3b82f6',
    end: '#9333ea',
    dotStyle: 'glitch',
    eyeStyle: 'cyberline',
    logo: 'Custom SVG',
  },
  {
    group: 'Experimental, Creative Showcase',
    name: 'Gradient Arc',
    start: '#fb7185',
    end: '#facc15',
    dotStyle: 'arc',
    eyeStyle: 'round',
    logo: 'Canvas mask',
  },
  {
    group: 'Experimental, Creative Showcase',
    name: 'Pixel Grid',
    start: '#9ca3af',
    end: '#ffffff',
    dotStyle: 'pixel',
    eyeStyle: 'square',
    logo: 'NFT / art',
  },
  {
    group: 'Experimental, Creative Showcase',
    name: 'Data Stream',
    start: '#06b6d4',
    end: '#f0fdfa',
    dotStyle: 'thin',
    eyeStyle: 'frame',
    logo: 'Analytics UI',
  },
  {
    group: 'Experimental, Creative Showcase',
    name: 'Aurora Storm',
    start: '#7e22ce',
    end: '#14b8a6',
    dotStyle: 'lightning',
    eyeStyle: 'frame bold',
    logo: 'Use blur shadow',
  },
];

export default qrStylePresets;
